CREATE PROCEDURE sp_CreateArcaOrder (
	@APPLICATION_PAYLOAD nvarchar(MAX)
)
AS
BEGIN
	INSERT INTO ARCA_PAYMENT_ORDER(APPLICATION_PAYLOAD, CREATED_DATE)
	SELECT @APPLICATION_PAYLOAD, GETUTCDATE()

	SELECT SCOPE_IDENTITY()
END
GO