create or alter procedure sp_GetFicoSettingParameters
AS
	select PAYMENT_HISTORY_YEAR, HAD_LOAN_YEAR, NEW_LOAN_MONTH, NEW_QUERY_MONTH, NEW_RATIO_MONTH, NON_BANK_INTEREST
	from FICO_SETTING_PARAMETER
GO
