if exists (select * from sys.objects where name='sp_GetMainApplication' and type='P')
	drop procedure dbo.sp_GetMainApplication
GO

create procedure dbo.sp_GetMainApplication(@ID	uniqueidentifier)
AS
	select  a.FINAL_AMOUNT,
			rtrim(a.PERIOD_TYPE_CODE) as PERIOD_TYPE_CODE,
			a.INTEREST,
			a.REPAY_DAY,
			isnull(a.GOODS_RECEIVING_CODE,'1') as GOODS_RECEIVING_CODE,
			a.GOODS_DELIVERY_ADDRESS,
			a.FIRST_NAME_EN,
			a.LAST_NAME_EN,
			a.MOBILE_PHONE_1,
			a.MOBILE_PHONE_2,
			a.FIXED_PHONE,
			a.EMAIL,
			a.BIRTH_PLACE_CODE,
			a.CITIZENSHIP_CODE,
			isnull(a.REGISTRATION_COUNTRY_CODE,	c.REGISTRATION_COUNTRY_CODE)as REGISTRATION_COUNTRY_CODE,
			isnull(a.REGISTRATION_STATE_CODE,	c.REGISTRATION_STATE_CODE)	as REGISTRATION_STATE_CODE,
			isnull(a.REGISTRATION_CITY_CODE,	c.REGISTRATION_CITY_CODE)	as REGISTRATION_CITY_CODE,
			isnull(a.REGISTRATION_STREET,		c.REGISTRATION_STREET)		as REGISTRATION_STREET,
			isnull(a.REGISTRATION_BUILDNUM,		c.REGISTRATION_BUILDNUM)	as REGISTRATION_BUILDNUM,
			isnull(a.REGISTRATION_APARTMENT,	c.REGISTRATION_APARTMENT)	as REGISTRATION_APARTMENT,
			isnull(a.CURRENT_COUNTRY_CODE,		c.CURRENT_COUNTRY_CODE)		as CURRENT_COUNTRY_CODE,
			isnull(a.CURRENT_STATE_CODE,		c.CURRENT_STATE_CODE)		as CURRENT_STATE_CODE,
			isnull(a.CURRENT_CITY_CODE,			c.CURRENT_CITY_CODE)		as CURRENT_CITY_CODE,
			isnull(a.CURRENT_STREET,			c.CURRENT_STREET)			as CURRENT_STREET,
			isnull(a.CURRENT_BUILDNUM,			c.CURRENT_BUILDNUM)			as CURRENT_BUILDNUM,
			isnull(a.CURRENT_APARTMENT,			c.CURRENT_APARTMENT)		as CURRENT_APARTMENT,
			a.COMMUNICATION_TYPE_CODE,
			a.COMPANY_NAME,
			a.COMPANY_PHONE,
			a.POSITION,
			a.MONTHLY_INCOME_CODE,
			a.WORKING_EXPERIENCE_CODE,
			a.FAMILY_STATUS_CODE,
			a.SHOP_CODE,
			a.PRODUCT_CATEGORY_CODE,
			a.LOAN_TEMPLATE_CODE,
			a.OVERDRAFT_TEMPLATE_CODE,
			a.STATUS_ID,
			a.LOAN_TYPE_ID
	from dbo.APPLICATION a
		join dbo.CUSTOMER_USER as c
		on c.APPLICATION_USER_ID = a.CUSTOMER_USER_ID
	where a.ID = @ID
GO
