if exists (select * from sys.objects where name='sp_GetCustomerUser' and type='P')
	drop procedure dbo.sp_GetCustomerUser
GO

create procedure dbo.sp_GetCustomerUser(@APPLICATION_USER_ID	int)
AS
	select FIRST_NAME_AM,
		   LAST_NAME_AM,
		   PATRONYMIC_NAME_AM,
		   FIRST_NAME_EN,
		   LAST_NAME_EN,
		   BIRTH_DATE,
		   MOBILE_PHONE,
		   MOBILE_PHONE_2,
		   FIXED_PHONE,
		   EMAIL,
		   SOCIAL_CARD_NUMBER,
		   DOCUMENT_TYPE_CODE,
		   DOCUMENT_NUMBER,
		   DOCUMENT_GIVEN_BY,
		   DOCUMENT_GIVEN_DATE,
		   DOCUMENT_EXPIRY_DATE,
		   BIRTH_PLACE_CODE,
		   CITIZENSHIP_CODE,
		   REGISTRATION_COUNTRY_CODE,
		   REGISTRATION_STATE_CODE,
		   REGISTRATION_CITY_CODE,
		   REGISTRATION_STREET,
		   REGISTRATION_BUILDNUM,
		   REGISTRATION_APARTMENT,
		   CURRENT_COUNTRY_CODE,
		   CURRENT_STATE_CODE,
		   CURRENT_CITY_CODE,
		   CURRENT_STREET,
		   CURRENT_BUILDNUM,
		   CURRENT_APARTMENT,
		   COMPANY_NAME,
		   COMPANY_PHONE,
		   ORGANIZATION_ACTIVITY_CODE,
		   POSITION,
		   MONTHLY_INCOME_CODE,
		   WORKING_EXPERIENCE_CODE,
		   FAMILY_STATUS_CODE,
		   CLIENT_CODE
	from dbo.CUSTOMER_USER
	where APPLICATION_USER_ID = @APPLICATION_USER_ID
GO
