create or alter procedure sp_SavePartnerCompanyScoring(
	@PARTNER_COMPANY_CODE	varchar(8)
	,@PRODUCT_CATEGORY_CODE	char(2)
	,@SCORECARD_CODE		varchar(3)
)
AS
	insert into PARTNER_COMPANY_SCORING(PARTNER_COMPANY_CODE, PRODUCT_CATEGORY_CODE, SCORECARD_CODE)
	values (@PARTNER_COMPANY_CODE, @PRODUCT_CATEGORY_CODE, @SCORECARD_CODE)
GO
