CREATE PROCEDURE sp_UpdateArcaOrderByOrderId (
	@ARCA_ORDER_ID nvarchar(64),
	@ERROR_CODE NVARCHAR(16) = NULL,
	@PAY_DATE DATETIME = NULL,
	@CARD_HOLDER_NAME NVARCHAR(128) = NULL,
	@STATUS NVARCHAR(16) = NULL,
	@IS_REFUNDED BIT = NULL
)
AS
BEGIN
	UPDATE ARCA_PAYMENT_ORDER
	SET ERROR_CODE = ISNULL(@ERROR_CODE, ERROR_CODE),
	PAY_DATE = ISNULL(@PAY_DATE, PAY_DATE),
	CARD_HOLDER_NAME = ISNULL(@CARD_HOLDER_NAME, CARD_HOLDER_NAME),
	[STATUS] = ISNULL(@STATUS, [STATUS]),
	IS_REFUNDED = ISNULL(@IS_REFUNDED, IS_REFUNDED)
	WHERE ARCA_ORDER_ID = @ARCA_ORDER_ID
END
GO