insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO)
	values ('01', 'EUR', 'TMP1', 'TEMPLATE TANE 1', 6, 18)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO)
	values ('01', 'USD', 'TMP1', 'TEMPLATE NAME 2', 12, 48)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO)
	values ('01', 'AMD', 'TMP3', 'TEMPLATE NAME 3', 24, 24)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO)
	values ('02', 'EUR', 'TMP4', 'TEMPLATE TANE 4', 6, 12)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO)
	values ('02', 'USD', 'TMP5', 'TEMPLATE NAME 5', 18, 48)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO)
	values ('02', 'AMD', 'TMP6', 'TEMPLATE NAME 6', 30, 30)
GO
