INSERT INTO dbo.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST)
	VALUES('01', '1', 'AMD', '', 0, 5)
GO
INSERT INTO dbo.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST)
	VALUES('01', '9', 'AMD', '', 0, 7)
GO
INSERT INTO dbo.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST)
	VALUES('02', '2', 'AMD', '', 0, 2)
GO
INSERT INTO dbo.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST)
	VALUES('02', '3', 'AMD', '', 0, 4)
GO
INSERT INTO dbo.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST)
	VALUES('02', '2', 'USD', '', 0, 4)
GO
INSERT INTO dbo.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST)
	VALUES('02', '3', 'USD', '', 0, 6)
GO
INSERT INTO dbo.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST)
	VALUES('02', '2', 'EUR', '', 0, 6)
GO
INSERT INTO dbo.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST)
	VALUES('02', '3', 'EUR', '', 0, 8)
GO
