insert into dbo.LOAN_LIMIT (LOAN_TYPE_CODE, CURRENCY, NAME_AM, NAME_EN, FROM_AMOUNT, TO_AMOUNT)
	values ('01', 'AMD', N'ՀՀ դրամ', 'RA Dram', 200000, 200000000)
GO
insert into dbo.LOAN_LIMIT (LOAN_TYPE_CODE, CURRENCY, NAME_AM, NAME_EN, FROM_AMOUNT, TO_AMOUNT)
	values ('02', 'AMD', N'ՀՀ դրամ', 'RA Dram', 100000, 100000000)
GO
insert into dbo.LOAN_LIMIT (LOAN_TYPE_CODE, CURRENCY, NAME_AM, NAME_EN, FROM_AMOUNT, TO_AMOUNT)
	values ('02', 'USD', N'ԱՄՆ դոլար', 'US Dollar', 500, 500000)
GO
insert into dbo.LOAN_LIMIT (LOAN_TYPE_CODE, CURRENCY, NAME_AM, NAME_EN, FROM_AMOUNT, TO_AMOUNT)
	values ('02', 'EUR', N'Եվրո', 'Euro', 700, 700000)
GO
