if exists (select * from sys.objects where name='APPLICATION_SCORING_RESULT' and type='U')
	drop table dbo.APPLICATION_SCORING_RESULT
GO

CREATE TABLE dbo.APPLICATION_SCORING_RESULT(
	APPLICATION_ID		uniqueidentifier	NOT NULL,
	SCORING_NUMBER		tinyint				NOT NULL,
	AMOUNT				money				NOT NULL,
	INTEREST			money				NULL,
	PREPAYMENT_AMOUNT	money				NULL,
	PREPAYMENT_INTEREST	money				NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_SCORING_RESULT1 ON dbo.APPLICATION_SCORING_RESULT(APPLICATION_ID,SCORING_NUMBER)
GO
