if exists (select * from sys.objects where name='APPLICATION_USER_OPERATION_LOG' and type='U')
	drop table dbo.APPLICATION_USER_OPERATION_LOG
GO

CREATE TABLE dbo.APPLICATION_USER_OPERATION_LOG (
	ID 					int IDENTITY(1,1)	NOT NULL,
	DATE				datetime			NOT NULL default getdate(),
	APPLICATION_USER_ID	int					NOT NULL,
	BANK_OBJECT_CODE	varchar(20)			NOT NULL,
	BANK_OPERATION_CODE	varchar(20)			NOT NULL,
	ENTITY_ID			int					NULL,
	OPERATION_DETAILS	nvarchar(max)		NOT NULL
)
GO

CREATE CLUSTERED INDEX iAPPLICATION_USER_OPERATION_LOG1 ON dbo.APPLICATION_USER_OPERATION_LOG(ID)
GO

CREATE INDEX iAPPLICATION_USER_OPERATION_LOG2 ON dbo.APPLICATION_USER_OPERATION_LOG(DATE, APPLICATION_USER_ID)
GO

CREATE INDEX iAPPLICATION_USER_OPERATION_LOG3 ON dbo.APPLICATION_USER_OPERATION_LOG(BANK_OBJECT_CODE, ENTITY_ID)
GO
