if exists (select * from sys.objects where name='CARD_RECEIVING_OPTIONS' and type='U')
	drop table dbo.CARD_RECEIVING_OPTIONS
GO

CREATE TABLE dbo.CARD_RECEIVING_OPTIONS (  -- TODO: Why do we need this?
	CODE 	char(1)			NOT NULL,
	NAME_AM	nvarchar(50)	NOT NULL,
	NAME_EN varchar(50)		NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iCARD_RECEIVING_OPTIONS1 ON dbo.CARD_RECEIVING_OPTIONS(CODE)
GO
