if exists (select * from sys.objects where name='CUSTOMER_USER' and type='U')
	drop table dbo.CUSTOMER_USER
GO

CREATE TABLE dbo.CUSTOMER_USER(
	APPLICATION_USER_ID			int				NOT NULL,
	FIRST_NAME_AM				nvarchar(20)	NULL,
	LAST_NAME_AM				nvarchar(20)	NULL,
	PATRONYMIC_NAME_AM			nvarchar(20)	NULL,
	FIRST_NAME_EN				varchar(20)		NULL,
	LAST_NAME_EN				varchar(20)		NULL,

	BIRTH_DATE					date			NULL,
	MOBILE_PHONE				varchar(20)		NOT NULL,
	MOBILE_PHONE_2				varchar(20)		NULL, -- TODO: maybe this is not needed because of FIXED_PHONE
	EMAIL						varchar(70)		NULL,
	FIXED_PHONE					varchar(20)		NULL,
	SOCIAL_CARD_NUMBER			char(10)		NOT NULL,
	DOCUMENT_TYPE_CODE			char(1)			NULL,
	DOCUMENT_NUMBER				char(9)			NULL,
	DOCUMENT_GIVEN_BY			char(3)			NULL,
	DOCUMENT_GIVEN_DATE			date			NULL,
	DOCUMENT_EXPIRY_DATE		date			NULL,
	BIRTH_PLACE_CODE			char(2)			NULL,
	CITIZENSHIP_CODE			char(2)			NULL,
	REGISTRATION_COUNTRY_CODE	char(2)			NULL,
	REGISTRATION_STATE_CODE		char(3)			NULL,
	REGISTRATION_CITY_CODE		char(9)			NULL,
	REGISTRATION_STREET			nvarchar(150)	NULL,
	REGISTRATION_BUILDNUM		nvarchar(30)	NULL,
	REGISTRATION_APARTMENT		nvarchar(30)	NULL,
	CURRENT_COUNTRY_CODE		char(2)			NULL,
	CURRENT_STATE_CODE			char(3)			NULL,
	CURRENT_CITY_CODE			char(9)			NULL,
	CURRENT_STREET				nvarchar(150)	NULL,
	CURRENT_BUILDNUM			nvarchar(30)	NULL,
	CURRENT_APARTMENT			nvarchar(30)	NULL,
	COMPANY_NAME				nvarchar(40)	NULL,
	COMPANY_PHONE				varchar(20)		NULL,
	ORGANIZATION_ACTIVITY_CODE	char(2)			NULL,
	POSITION					nvarchar(50)	NULL,
	MONTHLY_INCOME_CODE			char(1)			NULL,
	WORKING_EXPERIENCE_CODE		char(1)			NULL,
	FAMILY_STATUS_CODE			char(1)			NULL,
	CLIENT_CODE					char(8)			NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iCUSTOMER_USER1 ON dbo.CUSTOMER_USER (APPLICATION_USER_ID)
GO
