if exists (select * from sys.objects where name='MOBILE_PHONE_AUTHORIZATION' and type='U')
	drop table MOBILE_PHONE_AUTHORIZATION
GO

CREATE TABLE MOBILE_PHONE_AUTHORIZATION (
	MOBILE_PHONE	varchar(20)			NOT NULL,
	SMS_HASH		varchar(1000)		NOT NULL,
	SMS_SENT_DATE	datetime			NOT NULL default getdate(),
	SMS_COUNT		int					NOT NULL default 1
)
GO

CREATE UNIQUE CLUSTERED INDEX iMOBILE_PHONE_AUTHORIZATION1 ON MOBILE_PHONE_AUTHORIZATION (MOBILE_PHONE)
GO
