if exists (select * from sys.objects where name='ORGANIZATION_ACTIVITY' and type='U')
	drop table dbo.ORGANIZATION_ACTIVITY
GO

CREATE TABLE dbo.ORGANIZATION_ACTIVITY (
	CODE 	char(2)			NOT NULL,
	NAME_AM	nvarchar(50)	NOT NULL,
	NAME_EN varchar(50)		NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iORGANIZATION_ACTIVITY1 ON dbo.ORGANIZATION_ACTIVITY(CODE)
GO
