if exists (select * from sys.objects where name='PARTNER_COMPANY_SCORING' and type='U')
	drop table dbo.PARTNER_COMPANY_SCORING
GO

CREATE TABLE dbo.PARTNER_COMPANY_SCORING(
	PARTNER_COMPANY_CODE	varchar(8)	NOT NULL,
	PRODUCT_CATEGORY_CODE	char(2)		NOT NULL,
	SCORECARD_CODE			varchar(3)	NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iPARTNER_COMPANY_SCORING1 ON dbo.PARTNER_COMPANY_SCORING(PARTNER_COMPANY_CODE, PRODUCT_CATEGORY_CODE)
GO
