if exists (select * from sys.objects where name='SCORING_FICO_VALUE' and type='U')
	drop table dbo.SCORING_FICO_VALUE
GO

CREATE TABLE dbo.SCORING_FICO_VALUE (
	ID			int			identity(1,1),
	FACTOR_ID 	tinyint		NOT NULL,
	FROM_VALUE	money		NOT NULL,
	TO_VALUE	money		NOT NULL,
	SCORE		money		NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iSCORING_FICO_VALUE1 ON dbo.SCORING_FICO_VALUE(ID)
GO
CREATE INDEX iSCORING_FICO_VALUE2 ON dbo.SCORING_FICO_VALUE(FACTOR_ID,FROM_VALUE,TO_VALUE)
GO
